# Generated by Django 2.0.4 on 2018-11-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('userstatus', models.IntegerField(blank=True, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('lastupdated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customusers',
                'managed': False,
            },
        ),
    ]
