# Generated by Django 2.0.2 on 2019-10-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='poll_viewers',
        ),
    ]
