# Generated by Django 2.0.5 on 2018-06-11 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_admin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditvault',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audtivault_adminuser', to='api.AdminUser'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_category', to='api.SurveyCategory'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_user_question', to='api.Survey'),
        ),
        migrations.AlterField(
            model_name='surveyquestionorder',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question_key', to='api.SurveyQuestion'),
        ),
        migrations.AlterField(
            model_name='surveyquestionorder',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question_order', to='api.Survey'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='respondent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveyResponse_respondent', to='api.SurveyRespondent'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveyResponse_survey', to='api.Survey'),
        ),
        migrations.AlterField(
            model_name='surveyresponsechoice',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question_choice', to='api.SurveyQuestion'),
        ),
        migrations.AlterField(
            model_name='useractiontype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionType_adminuser', to='api.AdminUser'),
        ),
    ]
