# Generated by Django 2.0.2 on 2019-08-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votecount',
            name='poll_vote',
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='poll',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='has_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.SlugField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='VoteCount',
        ),
    ]
