# Generated by Django 2.0.2 on 2019-06-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote_anonymous_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_vote', to='polls.Poll'),
        ),
    ]
