# Generated by Django 2.0.4 on 2018-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181211_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='choice_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
    ]
