# Generated by Django 2.0.2 on 2019-09-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190806_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_audio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
