# Generated by Django 2.0.2 on 2019-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190918_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
