# Generated by Django 2.0.2 on 2019-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190918_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_audio',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_video',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
