# Generated by Django 2.0.2 on 2019-06-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_votecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecount',
            name='poll_vote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
