# Generated by Django 2.0.2 on 2019-06-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190624_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecount',
            name='poll_vote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll_vote_count', to='polls.Poll'),
        ),
    ]
