# Generated by Django 2.0.2 on 2019-11-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190918_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='has_expired',
        ),
    ]
