# Generated by Django 2.0.2 on 2020-04-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_poll_has_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
