# Generated by Django 2.0.2 on 2019-08-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190807_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_likes', to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='share',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_share', to='polls.Poll'),
        ),
    ]
