# Generated by Django 2.0.2 on 2019-03-04 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_auto_20190207_0954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookMarks',
            new_name='BookMark',
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ('-share_date',)},
        ),
        migrations.AlterField(
            model_name='share',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
