# Generated by Django 2.0.2 on 2019-08-08 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190806_1325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_auto_20190808_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ('-like_date',)},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('poll', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('poll', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('poll', 'user')},
        ),
    ]
