# Generated by Django 2.0.2 on 2019-08-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190808_0102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set(),
        ),
    ]
