# Generated by Django 2.0.2 on 2019-08-11 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190806_1325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0006_auto_20190808_0643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('poll', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('poll', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('poll', 'user')},
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
