# Generated by Django 2.0.2 on 2019-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20190811_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile2',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='userprofile.UserProfile2'),
        ),
    ]
