# Generated by Django 2.0.2 on 2019-08-17 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0008_userprofile2_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('place_of_work', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, max_length=1200, null=True)),
                ('follows', models.ManyToManyField(related_name='followed_by', to='userprofile.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile2',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='userprofile2',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile2',
        ),
    ]
