# Generated by Django 2.0.2 on 2019-08-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20190817_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
    ]
