# Generated by Django 2.0.2 on 2019-09-11 10:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_remove_profile_follows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='share',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='avatar/customer.png', max_length=255, verbose_name='images'),
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
