# Generated by Django 2.0.2 on 2019-08-09 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='date_of_follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='date_follow',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
