# Generated by Django 2.0.2 on 2019-02-14 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0002_failedsearch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FailedSearch',
            new_name='FailedSearchHistory',
        ),
        migrations.AlterModelOptions(
            name='failedsearchhistory',
            options={'verbose_name_plural': 'Failed Search Histories'},
        ),
    ]
