# Generated by Django 2.0.4 on 2019-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('mediafilename', models.CharField(max_length=50)),
                ('mediasource', models.CharField(blank=True, max_length=80, null=True)),
                ('media', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createddate', models.DateTimeField()),
            ],
            options={
                'db_table': 'media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFilesize',
            fields=[
                ('media_filesize_id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum_size', models.IntegerField()),
                ('maximum_size', models.IntegerField()),
            ],
            options={
                'db_table': 'media_filesize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('media_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'media_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyCategories',
            fields=[
                ('survey_categories_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'survey_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyChoiceImage',
            fields=[
                ('survey_choice_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'survey_choice_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyChoiceText',
            fields=[
                ('survey_choice_text_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.TextField()),
            ],
            options={
                'db_table': 'survey_choice_text',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('survey_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('opening_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'survey_question',
                'managed': False,
            },
        ),
    ]
