# Generated by Django 2.0.2 on 2019-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('devicename', models.CharField(blank=True, max_length=60, null=True)),
                ('ipaddress', models.GenericIPAddressField()),
                ('browsername', models.CharField(blank=True, max_length=30, null=True)),
                ('browserversion', models.CharField(blank=True, max_length=10, null=True)),
                ('operatingsystem', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
